print('Практическая работа по уроку "Организация программ и методы строк"')
my_string = input('Введите произвольную цитату: ')
#my_string = 'Нажми на кнопку - получишь результат'
print('\n2_1 my_string =',my_string)
print('\n2_2 Вывести количество символов введённого текста')
print(len(my_string))
print('\n3_1 Выведите строку my_string в верхнем регистре')
print(my_string.upper())
print(len(my_string))
print('\n3_2 Выведите строку my_string в нижнем регистре')
print(my_string.lower())
print('\n3_3 Измените строку my_string, удалив все пробелы')
print(my_string.replace(' ', ''))
print('\n3_4 Выведите первый символ строки my_string')
print(my_string[0])
print('\n3_5 Выведите последний символ строки my_string')
print(my_string[-1])
